site_name: Cozy Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy-docs-v3
edit_uri: edit/master/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_css: [css/extra.css, css/highlight_theme.css]
extra_javascript: [extra.js]
pages:
  - Home: index.md
  - Use:
    - "User guide": use/index.md
  - Synchronize:
    - 'Stay in sync': sync/index.md
    - 'Synchronize your phone': sync/phone.md
    - 'Synchronize your computer': sync/desktop.md
    - 'Install on GNU/Linux': sync/linux.md
  - Download: download/index.md
  - Install:
    - install/index.md
    - "Debian": install/debian.md
    - "Manual installation": install/manual.md
  - Develop:
    - "Let's hack some code": dev/index.md
    - "Architecture": dev/intro.md
    - "Create your first app": dev/app.md
    - "Develop a connector": dev/konnector.md
    - "Create a mobile app with cordova": dev/cordova.md
    - "How to send mail in development": dev/sendmail.md
  - References:
    - Cozy-konnector-libs:
      - "API" : cozy-konnector-libs/api.md
      - "CLI": cozy-konnector-libs/cli.md
      - "Develop": cozy-konnector-libs/dev.md
      - "Errors": cozy-konnector-libs/errors.md
      - "Operation linking": cozy-konnector-libs/operation-linking.md
      - "Synchronization": cozy-konnector-libs/synchronization.md
    - Cozy Stack:
        - Architecture:
          - "General overview": cozy-stack/architecture.md
          - Security: cozy-stack/security.md
        - Usage:
            - "Install the cozy-stack": cozy-stack/INSTALL.md
            - "Manpages of the command-line tool": cozy-stack/cli/cozy-stack.md
            - "Configuration file": cozy-stack/config.md
            - "Managing Instances": cozy-stack/instance.md
            - "Onboarding": cozy-stack/onboarding.md
        - For developpers:
            - "Develop a client-side app": cozy-stack/client-app-dev.md
            - "Running and building Docker images": cozy-stack/docker.md
            - "Build a release": cozy-stack/release.md
            - "The contributing guide": cozy-stack/CONTRIBUTING.md
        - Services:
            - "/auth - Authentication & OAuth": cozy-stack/auth.md
            - "/apps - Applications Management": cozy-stack/apps.md
                - "Apps registry": cozy-stack/registry.md
            - "/data - Data System": cozy-stack/data-system.md
                - "Mango": cozy-stack/mango.md
                - "Replication": cozy-stack/replication.md
                - "CouchDB Quirks": cozy-stack/couchdb-quirks.md
            - "/files - Virtual File System": cozy-stack/files.md
                - "References of documents in VFS": cozy-stack/references-docs-in-vfs.md
            - "/intents - Intents": cozy-stack/intents.md
            - "/jobs Jobs": cozy-stack/jobs.md
                - "Konnectors": cozy-stack/konnectors.md
                - "Workers": cozy-stack/workers.md
            - "/notifications - Notifications": cozy-stack/notifications.md
            - "/permissions - Permissions": cozy-stack/permissions.md
            - "/realtime - Realtime": cozy-stack/realtime.md
            - "/remote - Proxy for remote data/API": cozy-stack/remote.md
            - "/settings - Settings": cozy-stack/settings.md
            - "/sharings - Sharing": cozy-stack/sharing.md
                - "Request for comments": cozy-stack/sharing-design.md


theme: mkdocs
theme_dir: 'cozy-theme'
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - footnotes
  #- markdown_i18n:
  #    i18n_lang: en_US
  #    i18n_dir: i18n
  - sane_lists
  - smarty
  - toc:
      permalink: True
